; ============================================================
; boot.asm - FAT12 boot sector for a 1.44 MB floppy
;
; Finds KERNEL.SYS in the root directory, loads it at
; 0x1000:0000 (following the FAT12 cluster chain), then jumps
; to it with DL = boot drive number.
;
; Memory map while booting:
;   0x00600           free (kernel relocates itself here later)
;   0x07C00 - 0x07DFF this boot sector
;   0x08000 - 0x09BFF root directory buffer (14 sectors)
;   0x0A000 - 0x0B1FF FAT buffer (9 sectors)
;   0x10000 +         kernel load area (KERNEL_SEG:0000)
; ============================================================
[BITS 16]
[ORG 0x7C00]

KERNEL_SEG  equ 0x1000          ; kernel load segment
ROOT_BUF    equ 0x8000          ; root directory buffer (in segment 0)
FAT_BUF     equ 0xA000          ; FAT buffer (in segment 0)

	jmp short start
	nop

; --- BIOS Parameter Block (DOS 4.0 EBPB), 1.44 MB floppy ---
; OS_OEM (8 chars) / OS_VOL (11 chars) come from build\version.inc,
; generated by build.ps1 from version.h (single source of the name)
%include "version.inc"
bpbOem              db OS_OEM
bpbBytesPerSec      dw 512
bpbSecPerClus       db 1
bpbReservedSecs     dw 1
bpbNumFats          db 2
bpbRootEntries      dw 224
bpbTotalSecs        dw 2880
bpbMedia            db 0xF0
bpbSecsPerFat       dw 9
bpbSecsPerTrack     dw 18
bpbHeads            dw 2
bpbHiddenSecs       dd 0
bpbTotalSecs32      dd 0
bpbDriveNum         db 0
bpbReserved         db 0
bpbBootSig          db 0x29
bpbVolumeId         dd 0x20260609
bpbVolumeLabel      db OS_VOL
bpbFsType           db 'FAT12   '

start:
	jmp 0x0000:main             ; normalize CS:IP (some BIOSes use 07C0:0000)
main:
	cli
	xor ax, ax
	mov ds, ax
	mov es, ax
	mov ss, ax
	mov sp, 0x7C00              ; stack right below the boot sector
	sti
	mov [bpbDriveNum], dl       ; remember the boot drive

	; --- load root directory (14 sectors @ LBA 19) to ROOT_BUF ---
	mov ax, 19
	mov cx, 14
	mov bx, ROOT_BUF
.load_root:
	call read_sector
	inc ax
	add bx, 512
	loop .load_root

	; --- find KERNEL.SYS among the root entries ---
	mov di, ROOT_BUF
	mov cx, [bpbRootEntries]
.find:
	push cx
	mov si, kernel_name
	mov cx, 11
	push di
	repe cmpsb
	pop di
	pop cx
	je .found
	add di, 32
	loop .find
	mov si, msg_no_kernel
	jmp fail

.found:
	push word [di+26]           ; first cluster of KERNEL.SYS

	; --- load FAT #1 (9 sectors @ LBA 1) to FAT_BUF ---
	mov ax, 1
	mov cx, 9
	mov bx, FAT_BUF
.load_fat:
	call read_sector
	inc ax
	add bx, 512
	loop .load_fat

	; --- follow the cluster chain, loading sector by sector ---
	pop si                      ; SI = current cluster
	mov ax, KERNEL_SEG
	mov es, ax
.load_kernel:
	mov ax, si
	add ax, 31                  ; LBA = data_start(33) + cluster - 2
	xor bx, bx
	call read_sector
	mov ax, es                  ; advance destination by one sector
	add ax, 512/16              ; (bump segment so files >64 KB work)
	mov es, ax
	; next cluster = FAT12 entry of SI
	mov bx, si
	shr bx, 1
	add bx, si                  ; BX = cluster * 3 / 2 (floor)
	mov ax, [FAT_BUF+bx]
	test si, 1
	jz .even
	shr ax, 4
	jmp .next
.even:
	and ax, 0x0FFF
.next:
	mov si, ax
	cmp ax, 0xFF8               ; 0xFF8..0xFFF = end of chain
	jb .load_kernel

	; --- hand over to the kernel ---
	mov dl, [bpbDriveNum]
	jmp KERNEL_SEG:0

; ------------------------------------------------------------
; read_sector: read 1 sector. AX = LBA, ES:BX = destination.
; Preserves all registers. Halts via fail on disk error.
; ------------------------------------------------------------
read_sector:
	pusha
	xor dx, dx
	div word [bpbSecsPerTrack]  ; AX = LBA / SPT, DX = LBA % SPT
	inc dl
	mov cl, dl                  ; CL = sector (1-based)
	xor dx, dx
	div word [bpbHeads]         ; AX = cylinder, DX = head
	mov ch, al                  ; CH = cylinder
	mov dh, dl                  ; DH = head
	mov dl, [bpbDriveNum]
	mov ax, 0x0201              ; AH=02h read, AL=1 sector
	int 0x13
	jc .error
	popa
	ret
.error:
	mov si, msg_disk_err
	; fall through to fail

; --- fail: print DS:SI message, wait for a key, reboot ---
fail:
	lodsb
	test al, al
	jz .wait
	mov ah, 0x0E
	mov bx, 0x0007
	int 0x10
	jmp fail
.wait:
	xor ax, ax
	int 0x16
	int 0x19

kernel_name   db 'KERNEL  SYS'
msg_no_kernel db 'KERNEL.SYS not found', 13, 10, 0
msg_disk_err  db 'Disk read error', 13, 10, 0

	times 510-($-$$) db 0
	dw 0xAA55
